// <auto-generated/>

namespace CustomerManagement.Api.Context
{
  using CustomerManagement.Api.Models;
  using Microsoft.EntityFrameworkCore;

  public partial class DomainContext : DbContext
  {
    public DbSet<Customer> Customers { get; set; }
  }
}
